//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace OrderMotion {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UDOARequest {
        
        private UDOARequestParameter[] uDIParameterField;
        
        private UDOARequestHeader headerField;
        
        private UDOARequestCustomer customerField;
        
        private UDOARequestShippingInformation shippingInformationField;
        
        private Payment paymentField;
        
        private UDOARequestLineItem[] orderDetailField;
        
        private UDOARequestCustomFields customFieldsField;
        
        private UDOARequestCheck checkField;
        
        private UDOARequestVersion versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public UDOARequestParameter[] UDIParameter {
            get {
                return this.uDIParameterField;
            }
            set {
                this.uDIParameterField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestCustomer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestShippingInformation ShippingInformation {
            get {
                return this.shippingInformationField;
            }
            set {
                this.shippingInformationField = value;
            }
        }
        
        /// <remarks/>
        public Payment Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LineItem", IsNullable=false)]
        public UDOARequestLineItem[] OrderDetail {
            get {
                return this.orderDetailField;
            }
            set {
                this.orderDetailField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestCustomFields CustomFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestCheck Check {
            get {
                return this.checkField;
            }
            set {
                this.checkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UDOARequestVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestParameter {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressData {
        
        private string titleCodeField;
        
        private string companyField;
        
        private string firstnameField;
        
        private string midInitialField;
        
        private string lastnameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zIPField;
        
        private string tLDField;
        
        private string phoneNumberField;
        
        private string emailField;
        
        private string houseNoField;
        
        private string subCityField;
        
        private string buildingField;
        
        private string apartmentField;
        
        private string countryField;
        
        private string mSISDNField;
        
        private AddressDataType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string TitleCode {
            get {
                return this.titleCodeField;
            }
            set {
                this.titleCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string MidInitial {
            get {
                return this.midInitialField;
            }
            set {
                this.midInitialField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
            }
        }
        
        /// <remarks/>
        public string TLD {
            get {
                return this.tLDField;
            }
            set {
                this.tLDField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string HouseNo {
            get {
                return this.houseNoField;
            }
            set {
                this.houseNoField = value;
            }
        }
        
        /// <remarks/>
        public string SubCity {
            get {
                return this.subCityField;
            }
            set {
                this.subCityField = value;
            }
        }
        
        /// <remarks/>
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        public string Apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string MSISDN {
            get {
                return this.mSISDNField;
            }
            set {
                this.mSISDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AddressDataType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum AddressDataType {
        
        /// <remarks/>
        BillTo,
        
        /// <remarks/>
        ShipTo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestHeader {
        
        private string orderDateField;
        
        private UDOARequestHeaderOriginType originTypeField;
        
        private TrueFalse inquiryFlagField;
        
        private bool inquiryFlagFieldSpecified;
        
        private string orderIDField;
        
        private string storeCodeField;
        
        private string usernameField;
        
        private string siteIDField;
        
        private string clickIDField;
        
        private string batchNumberField;
        
        private string batchDateField;
        
        private string referenceField;
        
        private string oMUsernameField;
        
        private string retailStoreCodeField;
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestHeaderOriginType OriginType {
            get {
                return this.originTypeField;
            }
            set {
                this.originTypeField = value;
            }
        }
        
        /// <remarks/>
        public TrueFalse InquiryFlag {
            get {
                return this.inquiryFlagField;
            }
            set {
                this.inquiryFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InquiryFlagSpecified {
            get {
                return this.inquiryFlagFieldSpecified;
            }
            set {
                this.inquiryFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public string StoreCode {
            get {
                return this.storeCodeField;
            }
            set {
                this.storeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClickID {
            get {
                return this.clickIDField;
            }
            set {
                this.clickIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string BatchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
        
        /// <remarks/>
        public string BatchDate {
            get {
                return this.batchDateField;
            }
            set {
                this.batchDateField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string OMUsername {
            get {
                return this.oMUsernameField;
            }
            set {
                this.oMUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string RetailStoreCode {
            get {
                return this.retailStoreCodeField;
            }
            set {
                this.retailStoreCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UDOARequestHeaderOriginType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum TrueFalse {
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestCustomer {
        
        private AddressData addressField;
        
        private string usernameField;
        
        private string passwordField;
        
        private UDOARequestCustomerFlag[] flagDataField;
        
        private string customerNumberField;
        
        /// <remarks/>
        public AddressData Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Flag", IsNullable=false)]
        public UDOARequestCustomerFlag[] FlagData {
            get {
                return this.flagDataField;
            }
            set {
                this.flagDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string customerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestCustomerFlag {
        
        private UDOARequestCustomerFlagName nameField;
        
        private TrueFalse valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UDOARequestCustomerFlagName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public TrueFalse Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UDOARequestCustomerFlagName {
        
        /// <remarks/>
        DoNotMail,
        
        /// <remarks/>
        DoNotEmail,
        
        /// <remarks/>
        DoNotCall,
        
        /// <remarks/>
        Nixie,
        
        /// <remarks/>
        BadDebt,
        
        /// <remarks/>
        DoNotRent,
        
        /// <remarks/>
        Deceased,
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        NoAVS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestShippingInformation {
        
        private AddressData addressField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private float shippingAmountField;
        
        private bool shippingAmountFieldSpecified;
        
        private float handlingAmountField;
        
        private bool handlingAmountFieldSpecified;
        
        private string specialInstructionsField;
        
        private TrueFalse giftWrappingField;
        
        private bool giftWrappingFieldSpecified;
        
        private string giftMessageField;
        
        /// <remarks/>
        public AddressData Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MethodCode", typeof(string), DataType="nonNegativeInteger")]
        [System.Xml.Serialization.XmlElementAttribute("MethodName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public float ShippingAmount {
            get {
                return this.shippingAmountField;
            }
            set {
                this.shippingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingAmountSpecified {
            get {
                return this.shippingAmountFieldSpecified;
            }
            set {
                this.shippingAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public float HandlingAmount {
            get {
                return this.handlingAmountField;
            }
            set {
                this.handlingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HandlingAmountSpecified {
            get {
                return this.handlingAmountFieldSpecified;
            }
            set {
                this.handlingAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SpecialInstructions {
            get {
                return this.specialInstructionsField;
            }
            set {
                this.specialInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public TrueFalse GiftWrapping {
            get {
                return this.giftWrappingField;
            }
            set {
                this.giftWrappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GiftWrappingSpecified {
            get {
                return this.giftWrappingFieldSpecified;
            }
            set {
                this.giftWrappingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string GiftMessage {
            get {
                return this.giftMessageField;
            }
            set {
                this.giftMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        MethodCode,
        
        /// <remarks/>
        MethodName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Payment {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private PaymentAdditionalPayment additionalPaymentField;
        
        private PaymentType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BankAccountNumber", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("BankRoutingNumber", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("BuyerEmail", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CardAVSResult", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CardAuthCode", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CardExpDateDay", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("CardExpDateMonth", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("CardExpDateYear", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("CardIssueNumber", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CardNumber", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CardStartDateMonth", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("CardStartDateYear", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("CardStatus", typeof(PaymentCardStatus))]
        [System.Xml.Serialization.XmlElementAttribute("CardTransactionID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CardVerification", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("CheckNumber", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("GiftCertificateCode", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PaidAmount", typeof(float))]
        [System.Xml.Serialization.XmlElementAttribute("PayerID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PaymentPlanID", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("RealTimeCreditCardProcessing", typeof(TrueFalse))]
        [System.Xml.Serialization.XmlElementAttribute("TransactionID", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        public PaymentAdditionalPayment AdditionalPayment {
            get {
                return this.additionalPaymentField;
            }
            set {
                this.additionalPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PaymentType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PaymentCardStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        BankAccountNumber,
        
        /// <remarks/>
        BankRoutingNumber,
        
        /// <remarks/>
        BuyerEmail,
        
        /// <remarks/>
        CardAVSResult,
        
        /// <remarks/>
        CardAuthCode,
        
        /// <remarks/>
        CardExpDateDay,
        
        /// <remarks/>
        CardExpDateMonth,
        
        /// <remarks/>
        CardExpDateYear,
        
        /// <remarks/>
        CardIssueNumber,
        
        /// <remarks/>
        CardNumber,
        
        /// <remarks/>
        CardStartDateMonth,
        
        /// <remarks/>
        CardStartDateYear,
        
        /// <remarks/>
        CardStatus,
        
        /// <remarks/>
        CardTransactionID,
        
        /// <remarks/>
        CardVerification,
        
        /// <remarks/>
        CheckNumber,
        
        /// <remarks/>
        GiftCertificateCode,
        
        /// <remarks/>
        PaidAmount,
        
        /// <remarks/>
        PayerID,
        
        /// <remarks/>
        PaymentPlanID,
        
        /// <remarks/>
        RealTimeCreditCardProcessing,
        
        /// <remarks/>
        TransactionID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PaymentAdditionalPayment {
        
        private Payment[] paymentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Payment")]
        public Payment[] Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PaymentType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestLineItem {
        
        private string itemCodeField;
        
        private UDOARequestLineItemDimension[] dimensionField;
        
        private string quantityField;
        
        private float unitPriceField;
        
        private bool unitPriceFieldSpecified;
        
        private string infoField;
        
        private UDOARequestLineItemRecurrence recurrenceField;
        
        private string waitDateField;
        
        private UDOARequestLineItemLineStatus lineStatusField;
        
        private string shippedDateField;
        
        private string lineNumberField;
        
        public UDOARequestLineItem() {
            this.lineStatusField = UDOARequestLineItemLineStatus.Item0;
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dimension")]
        public UDOARequestLineItemDimension[] Dimension {
            get {
                return this.dimensionField;
            }
            set {
                this.dimensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public float UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitPriceSpecified {
            get {
                return this.unitPriceFieldSpecified;
            }
            set {
                this.unitPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestLineItemRecurrence Recurrence {
            get {
                return this.recurrenceField;
            }
            set {
                this.recurrenceField = value;
            }
        }
        
        /// <remarks/>
        public string WaitDate {
            get {
                return this.waitDateField;
            }
            set {
                this.waitDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(UDOARequestLineItemLineStatus.Item0)]
        public UDOARequestLineItemLineStatus LineStatus {
            get {
                return this.lineStatusField;
            }
            set {
                this.lineStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ShippedDate {
            get {
                return this.shippedDateField;
            }
            set {
                this.shippedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestLineItemDimension {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestLineItemRecurrence {
        
        private string patternIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string patternID {
            get {
                return this.patternIDField;
            }
            set {
                this.patternIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UDOARequestLineItemLineStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestCustomFields {
        
        private UDOARequestCustomFieldsDemographics demographicsField;
        
        private UDOARequestCustomFieldsField[] reportField;
        
        /// <remarks/>
        public UDOARequestCustomFieldsDemographics Demographics {
            get {
                return this.demographicsField;
            }
            set {
                this.demographicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public UDOARequestCustomFieldsField[] Report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestCustomFieldsDemographics {
        
        private string dateOfBirthField;
        
        private UDOARequestCustomFieldsDemographicsPlaceOfBirth placeOfBirthField;
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public UDOARequestCustomFieldsDemographicsPlaceOfBirth PlaceOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestCustomFieldsDemographicsPlaceOfBirth {
        
        private string cityField;
        
        private string stateField;
        
        private string tLDField;
        
        private string codeField;
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string TLD {
            get {
                return this.tLDField;
            }
            set {
                this.tLDField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestCustomFieldsField {
        
        private string fieldIDField;
        
        private string lineNumberField;
        
        private string fieldNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string fieldID {
            get {
                return this.fieldIDField;
            }
            set {
                this.fieldIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UDOARequestCheck {
        
        private float totalAmountField;
        
        /// <remarks/>
        public float TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UDOARequestVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.00")]
        Item200,
    }
}
