<%@ Page Language="C#" Theme="Admin" StylesheetTheme="Admin" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="admin_shipping.aspx.cs" Inherits="Admin_admin_shipping" Title="Shipping Calculator Administration" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminPlaceHolder" Runat="Server">
<div id="centercontent">
    <h4>Shipping Calculator</h4>
    <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="shippingRateID"
        DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="Service" HeaderText="Service" SortExpression="Service" />
            <asp:BoundField DataField="AmountPerUnit" HeaderText="Rate/Unit" SortExpression="AmountPerUnit" />
        </Columns>
    </asp:GridView>
    <br />
    <h4>Add Shipping Rate</h4><br />
    <asp:FormView ID="FormView1" runat="server" DataKeyNames="shippingRateID" DataSourceID="SqlDataSource1"
        DefaultMode="Insert">
         <InsertItemTemplate>
            Service<br />
            <asp:TextBox ID="ServiceTextBox" runat="server" Text='<%# Bind("Service") %>'>
            </asp:TextBox><br />
            Amount Per Unit<br />
            <asp:TextBox ID="DollarsPerPoundTextBox" runat="server" Text='<%# Bind("AmountPerUnit") %>'>
            </asp:TextBox><br /><br />
            <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert"
                Text="Insert">
            </asp:LinkButton>
        </InsertItemTemplate>
    </asp:FormView>
    <br />
    <br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceTemplate %>"
        DeleteCommand="DELETE FROM [CSK_Shipping_Rate] WHERE [shippingRateID] = @shippingRateID"
        InsertCommand="INSERT INTO [CSK_Shipping_Rate] ([Service], [AmountPerUnit]) VALUES (@Service, @AmountPerUnit)"
        SelectCommand="SELECT [shippingRateID], [Service], [AmountPerUnit] FROM [CSK_Shipping_Rate]"
        UpdateCommand="UPDATE [CSK_Shipping_Rate] SET [Service] = @Service, [AmountPerUnit] = @AmountPerUnit WHERE [shippingRateID] = @shippingRateID">
        <DeleteParameters>
            <asp:Parameter Name="shippingRateID" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Service" Type="String" />
            <asp:Parameter Name="AmountPerUnit" Type="Decimal" />
            <asp:Parameter Name="original_shippingRateID" Type="Int32" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="Service" Type="String" />
            <asp:Parameter Name="AmountPerUnit" Type="Decimal" />
        </InsertParameters>
    </asp:SqlDataSource>

</div>

</asp:Content>

